// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeletePlaylistByIdData, DeletePlaylistByIdErrors, DeletePlaylistByIdResponses, DeletePlaylistData, DeletePlaylistErrors, DeletePlaylistResponses, GetPlaylistByIdExclusionsData, GetPlaylistByIdExclusionsErrors, GetPlaylistByIdExclusionsResponses, GetPlaylistByIdInclusionsData, GetPlaylistByIdInclusionsErrors, GetPlaylistByIdInclusionsResponses, GetPlaylistByIdPlaylistsData, GetPlaylistByIdPlaylistsErrors, GetPlaylistByIdPlaylistsResponses, GetPlaylistData, GetPlaylistErrors, GetPlaylistResponses, PostPlaylistData, PostPlaylistErrors, PostPlaylistIncludeData, PostPlaylistIncludeErrors, PostPlaylistIncludeResponses, PostPlaylistIncludeUndoData, PostPlaylistIncludeUndoErrors, PostPlaylistIncludeUndoResponses, PostPlaylistItemData, PostPlaylistItemErrors, PostPlaylistItemResponses, PostPlaylistItemUndoData, PostPlaylistItemUndoErrors, PostPlaylistItemUndoResponses, PostPlaylistPublishallData, PostPlaylistPublishallErrors, PostPlaylistPublishallResponses, PostPlaylistPublishData, PostPlaylistPublishErrors, PostPlaylistPublishResponses, PostPlaylistResponses, PostSearchData, PostSearchErrors, PostSearchResponses, PostSpotifyAlbumTracksData, PostSpotifyAlbumTracksErrors, PostSpotifyAlbumTracksResponses, PostSpotifyArtistAlbumsData, PostSpotifyArtistAlbumsErrors, PostSpotifyArtistAlbumsResponses, PutPlaylistByIdRenameData, PutPlaylistByIdRenameErrors, PutPlaylistByIdRenameResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Clear all playlists
 *
 * Deletes every playlist record in the database
 */
export const deletePlaylist = <ThrowOnError extends boolean = false>(options?: Options<DeletePlaylistData, ThrowOnError>) => (options?.client ?? client).delete<DeletePlaylistResponses, DeletePlaylistErrors, ThrowOnError>({ url: '/playlist', ...options });

/**
 * Get all playlists
 *
 * Responds with the list of all playlists as JSON.
 */
export const getPlaylist = <ThrowOnError extends boolean = false>(options?: Options<GetPlaylistData, ThrowOnError>) => (options?.client ?? client).get<GetPlaylistResponses, GetPlaylistErrors, ThrowOnError>({ url: '/playlist', ...options });

/**
 * Create new playlist
 *
 * Create a new playlist locally and on Spotify
 */
export const postPlaylist = <ThrowOnError extends boolean = false>(options: Options<PostPlaylistData, ThrowOnError>) => (options.client ?? client).post<PostPlaylistResponses, PostPlaylistErrors, ThrowOnError>({
    url: '/playlist',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Nest a Playlist
 *
 * Includes one playlist inside another parent playlist
 */
export const postPlaylistInclude = <ThrowOnError extends boolean = false>(options: Options<PostPlaylistIncludeData, ThrowOnError>) => (options.client ?? client).post<PostPlaylistIncludeResponses, PostPlaylistIncludeErrors, ThrowOnError>({
    url: '/playlist/include',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Undo a nested Playlist
 *
 * Undoes inclusion of one playlist inside another parent playlist
 */
export const postPlaylistIncludeUndo = <ThrowOnError extends boolean = false>(options: Options<PostPlaylistIncludeUndoData, ThrowOnError>) => (options.client ?? client).post<PostPlaylistIncludeUndoResponses, PostPlaylistIncludeUndoErrors, ThrowOnError>({
    url: '/playlist/include/undo',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Include or Exclude an Item
 *
 * Adds an IdItem to either the inclusions or exclusions of a playlist
 */
export const postPlaylistItem = <ThrowOnError extends boolean = false>(options: Options<PostPlaylistItemData, ThrowOnError>) => (options.client ?? client).post<PostPlaylistItemResponses, PostPlaylistItemErrors, ThrowOnError>({
    url: '/playlist/item',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Undo Include or Exclude
 *
 * Removes an IdItem from both inclusions and exclusions of a playlist
 */
export const postPlaylistItemUndo = <ThrowOnError extends boolean = false>(options: Options<PostPlaylistItemUndoData, ThrowOnError>) => (options.client ?? client).post<PostPlaylistItemUndoResponses, PostPlaylistItemUndoErrors, ThrowOnError>({
    url: '/playlist/item/undo',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Publish a playlist to Spotify
 *
 * Calculates the current tracklist based on inclusions/exclusions and replaces the Spotify playlist content.
 */
export const postPlaylistPublish = <ThrowOnError extends boolean = false>(options: Options<PostPlaylistPublishData, ThrowOnError>) => (options.client ?? client).post<PostPlaylistPublishResponses, PostPlaylistPublishErrors, ThrowOnError>({
    url: '/playlist/publish',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Publish all playlists to Spotify
 *
 * Calculates the current tracklist based on inclusions/exclusions and replaces the Spotify playlist content.
 */
export const postPlaylistPublishall = <ThrowOnError extends boolean = false>(options?: Options<PostPlaylistPublishallData, ThrowOnError>) => (options?.client ?? client).post<PostPlaylistPublishallResponses, PostPlaylistPublishallErrors, ThrowOnError>({ url: '/playlist/publishall', ...options });

/**
 * Delete a playlist
 *
 * Delete a specific playlist by its ID
 */
export const deletePlaylistById = <ThrowOnError extends boolean = false>(options: Options<DeletePlaylistByIdData, ThrowOnError>) => (options.client ?? client).delete<DeletePlaylistByIdResponses, DeletePlaylistByIdErrors, ThrowOnError>({ url: '/playlist/{id}', ...options });

/**
 * Get all excluded items for a playlist
 *
 * Fetches the list of all Artists, Albums, and Tracks manually excluded in a specific playlist.
 */
export const getPlaylistByIdExclusions = <ThrowOnError extends boolean = false>(options: Options<GetPlaylistByIdExclusionsData, ThrowOnError>) => (options.client ?? client).get<GetPlaylistByIdExclusionsResponses, GetPlaylistByIdExclusionsErrors, ThrowOnError>({ url: '/playlist/{id}/exclusions', ...options });

/**
 * Get all included items for a playlist
 *
 * Fetches the list of all Playlists, Artists, Albums, and Tracks manually included in a specific playlist.
 */
export const getPlaylistByIdInclusions = <ThrowOnError extends boolean = false>(options: Options<GetPlaylistByIdInclusionsData, ThrowOnError>) => (options.client ?? client).get<GetPlaylistByIdInclusionsResponses, GetPlaylistByIdInclusionsErrors, ThrowOnError>({ url: '/playlist/{id}/inclusions', ...options });

/**
 * Get all playlists as itemresponse items
 *
 * Responds with the list of all playlists as JSON.
 */
export const getPlaylistByIdPlaylists = <ThrowOnError extends boolean = false>(options: Options<GetPlaylistByIdPlaylistsData, ThrowOnError>) => (options.client ?? client).get<GetPlaylistByIdPlaylistsResponses, GetPlaylistByIdPlaylistsErrors, ThrowOnError>({ url: '/playlist/{id}/playlists', ...options });

/**
 * Rename a playlist
 *
 * Updates the display name of a playlist in the local database.
 */
export const putPlaylistByIdRename = <ThrowOnError extends boolean = false>(options: Options<PutPlaylistByIdRenameData, ThrowOnError>) => (options.client ?? client).put<PutPlaylistByIdRenameResponses, PutPlaylistByIdRenameErrors, ThrowOnError>({
    url: '/playlist/{id}/rename',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Unified Spotify Search
 *
 * Search Spotify for Artists, Albums, or Tracks based on the provided ItemType.
 */
export const postSearch = <ThrowOnError extends boolean = false>(options: Options<PostSearchData, ThrowOnError>) => (options.client ?? client).post<PostSearchResponses, PostSearchErrors, ThrowOnError>({
    url: '/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Tracks by Album
 *
 * Fetches all tracks for a specific Spotify album
 */
export const postSpotifyAlbumTracks = <ThrowOnError extends boolean = false>(options: Options<PostSpotifyAlbumTracksData, ThrowOnError>) => (options.client ?? client).post<PostSpotifyAlbumTracksResponses, PostSpotifyAlbumTracksErrors, ThrowOnError>({
    url: '/spotify/album/tracks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Albums by Artist
 *
 * Fetches albums and singles from Spotify for a specific artist
 */
export const postSpotifyArtistAlbums = <ThrowOnError extends boolean = false>(options: Options<PostSpotifyArtistAlbumsData, ThrowOnError>) => (options.client ?? client).post<PostSpotifyArtistAlbumsResponses, PostSpotifyArtistAlbumsErrors, ThrowOnError>({
    url: '/spotify/artist/albums',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
