// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeletePlaylistByIdData, DeletePlaylistByIdErrors, DeletePlaylistByIdResponses, DeletePlaylistData, DeletePlaylistErrors, DeletePlaylistResponses, GetPlaylistData, GetPlaylistErrors, GetPlaylistResponses, PostPlaylistData, PostPlaylistErrors, PostPlaylistResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Clear all playlists
 *
 * Deletes every playlist record in the database
 */
export const deletePlaylist = <ThrowOnError extends boolean = false>(options?: Options<DeletePlaylistData, ThrowOnError>) => (options?.client ?? client).delete<DeletePlaylistResponses, DeletePlaylistErrors, ThrowOnError>({ url: '/playlist', ...options });

/**
 * Get all playlists
 *
 * Responds with the list of all playlists as JSON.
 */
export const getPlaylist = <ThrowOnError extends boolean = false>(options?: Options<GetPlaylistData, ThrowOnError>) => (options?.client ?? client).get<GetPlaylistResponses, GetPlaylistErrors, ThrowOnError>({ url: '/playlist', ...options });

/**
 * Create new playlist
 *
 * Create a new playlist locally and on Spotify
 */
export const postPlaylist = <ThrowOnError extends boolean = false>(options: Options<PostPlaylistData, ThrowOnError>) => (options.client ?? client).post<PostPlaylistResponses, PostPlaylistErrors, ThrowOnError>({
    url: '/playlist',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a playlist
 *
 * Delete a specific playlist by its ID
 */
export const deletePlaylistById = <ThrowOnError extends boolean = false>(options: Options<DeletePlaylistByIdData, ThrowOnError>) => (options.client ?? client).delete<DeletePlaylistByIdResponses, DeletePlaylistByIdErrors, ThrowOnError>({ url: '/playlist/{id}', ...options });
