// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/api/v1' | (string & {});
};

export type GinH = {
    [key: string]: unknown;
};

export type ModelIdItem = {
    id?: string;
    itemType?: ModelItemType;
    playlists?: Array<ModelPlaylist>;
};

export type ModelInclusionType = 0 | 1 | 2;

export type ModelItemInclusionRequest = {
    include: boolean;
    playlistid: string;
    spotid: string;
    type: ModelItemType;
};

export type ModelItemPlaylistRequest = {
    cspotid: string;
    pspotid: string;
};

export type ModelItemRequest = {
    artistid: string;
    playlistid: string;
    type: ModelItemType;
};

export type ModelItemResponse = {
    icon?: Array<SpotifyImage>;
    included?: ModelInclusionType;
    itemType?: ModelItemType;
    name?: string;
    spotifyID?: string;
};

export type ModelItemType = 0 | 1 | 2 | 3;

export type ModelPlaylist = {
    exclusions?: Array<ModelIdItem>;
    id?: string;
    includedIn?: Array<ModelPlaylist>;
    includedPlaylists?: Array<ModelPlaylist>;
    inclusions?: Array<ModelIdItem>;
    name?: string;
};

export type ModelPlaylistCreateRequest = {
    name: string;
};

export type ModelPlaylistResponse = {
    exclusions?: Array<ModelIdItem>;
    includedPlaylists?: Array<ModelPlaylist>;
    inclusions?: Array<ModelIdItem>;
    name?: string;
    spotifyID?: string;
};

export type ModelSearchRequest = {
    playlistid: string;
    query: string;
    type: ModelItemType;
};

export type SpotifyImage = {
    /**
     * The image height, in pixels.
     */
    height?: number;
    /**
     * The source URL of the image.
     */
    url?: string;
    /**
     * The image width, in pixels.
     */
    width?: number;
};

export type DeletePlaylistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/playlist';
};

export type DeletePlaylistErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type DeletePlaylistError = DeletePlaylistErrors[keyof DeletePlaylistErrors];

export type DeletePlaylistResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeletePlaylistResponse = DeletePlaylistResponses[keyof DeletePlaylistResponses];

export type GetPlaylistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/playlist';
};

export type GetPlaylistErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetPlaylistError = GetPlaylistErrors[keyof GetPlaylistErrors];

export type GetPlaylistResponses = {
    /**
     * OK
     */
    200: Array<ModelPlaylist>;
};

export type GetPlaylistResponse = GetPlaylistResponses[keyof GetPlaylistResponses];

export type PostPlaylistData = {
    /**
     * Playlist name
     */
    body: ModelPlaylistCreateRequest;
    path?: never;
    query?: never;
    url: '/playlist';
};

export type PostPlaylistErrors = {
    /**
     * Bad Request
     */
    400: GinH;
};

export type PostPlaylistError = PostPlaylistErrors[keyof PostPlaylistErrors];

export type PostPlaylistResponses = {
    /**
     * Created
     */
    201: ModelPlaylistResponse;
};

export type PostPlaylistResponse = PostPlaylistResponses[keyof PostPlaylistResponses];

export type PostPlaylistIncludeData = {
    /**
     * Playlist Linking Details
     */
    body: ModelItemPlaylistRequest;
    path?: never;
    query?: never;
    url: '/playlist/include';
};

export type PostPlaylistIncludeErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostPlaylistIncludeError = PostPlaylistIncludeErrors[keyof PostPlaylistIncludeErrors];

export type PostPlaylistIncludeResponses = {
    /**
     * OK
     */
    200: ModelPlaylistResponse;
};

export type PostPlaylistIncludeResponse = PostPlaylistIncludeResponses[keyof PostPlaylistIncludeResponses];

export type PostPlaylistItemData = {
    /**
     * Inclusion/Exclusion Details
     */
    body: ModelItemInclusionRequest;
    path?: never;
    query?: never;
    url: '/playlist/item';
};

export type PostPlaylistItemErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostPlaylistItemError = PostPlaylistItemErrors[keyof PostPlaylistItemErrors];

export type PostPlaylistItemResponses = {
    /**
     * OK
     */
    200: ModelPlaylistResponse;
};

export type PostPlaylistItemResponse = PostPlaylistItemResponses[keyof PostPlaylistItemResponses];

export type DeletePlaylistByIdData = {
    body?: never;
    path: {
        /**
         * Playlist ID
         */
        id: string;
    };
    query?: never;
    url: '/playlist/{id}';
};

export type DeletePlaylistByIdErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type DeletePlaylistByIdError = DeletePlaylistByIdErrors[keyof DeletePlaylistByIdErrors];

export type DeletePlaylistByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostSearchData = {
    /**
     * Search Query and Item Type
     */
    body: ModelSearchRequest;
    path?: never;
    query?: never;
    url: '/search';
};

export type PostSearchErrors = {
    /**
     * Invalid Item Type
     */
    400: {
        [key: string]: string;
    };
};

export type PostSearchError = PostSearchErrors[keyof PostSearchErrors];

export type PostSearchResponses = {
    /**
     * OK
     */
    200: Array<ModelItemResponse>;
};

export type PostSearchResponse = PostSearchResponses[keyof PostSearchResponses];

export type PostSpotifyAlbumTracksData = {
    /**
     * Album and Playlist Context
     */
    body: ModelItemRequest;
    path?: never;
    query?: never;
    url: '/spotify/album/tracks';
};

export type PostSpotifyAlbumTracksErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostSpotifyAlbumTracksError = PostSpotifyAlbumTracksErrors[keyof PostSpotifyAlbumTracksErrors];

export type PostSpotifyAlbumTracksResponses = {
    /**
     * OK
     */
    200: Array<ModelItemResponse>;
};

export type PostSpotifyAlbumTracksResponse = PostSpotifyAlbumTracksResponses[keyof PostSpotifyAlbumTracksResponses];

export type PostSpotifyArtistAlbumsData = {
    /**
     * Artist and Playlist Context
     */
    body: ModelItemRequest;
    path?: never;
    query?: never;
    url: '/spotify/artist/albums';
};

export type PostSpotifyArtistAlbumsErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostSpotifyArtistAlbumsError = PostSpotifyArtistAlbumsErrors[keyof PostSpotifyArtistAlbumsErrors];

export type PostSpotifyArtistAlbumsResponses = {
    /**
     * OK
     */
    200: Array<ModelItemResponse>;
};

export type PostSpotifyArtistAlbumsResponse = PostSpotifyArtistAlbumsResponses[keyof PostSpotifyArtistAlbumsResponses];
