// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/api/v1' | (string & {});
};

export type GinH = {
    [key: string]: unknown;
};

export type GormDeletedAt = {
    time?: string;
    /**
     * Valid is true if Time is not NULL
     */
    valid?: boolean;
};

export type ModelIdItem = {
    createdAt?: string;
    deletedAt?: GormDeletedAt;
    id?: number;
    itemType?: ModelItemType;
    playlistID?: number;
    spotifyID?: string;
    updatedAt?: string;
};

export type ModelItemType = 0 | 1 | 2 | 3;

export type ModelPlaylist = {
    createdAt?: string;
    deletedAt?: GormDeletedAt;
    exclusions?: Array<ModelIdItem>;
    id?: number;
    includedPlaylists?: Array<ModelPlaylist>;
    inclusions?: Array<ModelIdItem>;
    name?: string;
    spotifyID?: string;
    updatedAt?: string;
};

export type ModelPlaylistCreateRequest = {
    name: string;
};

export type DeletePlaylistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/playlist';
};

export type DeletePlaylistErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type DeletePlaylistError = DeletePlaylistErrors[keyof DeletePlaylistErrors];

export type DeletePlaylistResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeletePlaylistResponse = DeletePlaylistResponses[keyof DeletePlaylistResponses];

export type GetPlaylistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/playlist';
};

export type GetPlaylistErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetPlaylistError = GetPlaylistErrors[keyof GetPlaylistErrors];

export type GetPlaylistResponses = {
    /**
     * OK
     */
    200: Array<ModelPlaylist>;
};

export type GetPlaylistResponse = GetPlaylistResponses[keyof GetPlaylistResponses];

export type PostPlaylistData = {
    /**
     * Playlist name
     */
    body: ModelPlaylistCreateRequest;
    path?: never;
    query?: never;
    url: '/playlist';
};

export type PostPlaylistErrors = {
    /**
     * Bad Request
     */
    400: GinH;
};

export type PostPlaylistError = PostPlaylistErrors[keyof PostPlaylistErrors];

export type PostPlaylistResponses = {
    /**
     * Created
     */
    201: ModelPlaylist;
};

export type PostPlaylistResponse = PostPlaylistResponses[keyof PostPlaylistResponses];

export type DeletePlaylistByIdData = {
    body?: never;
    path: {
        /**
         * Playlist ID
         */
        id: string;
    };
    query?: never;
    url: '/playlist/{id}';
};

export type DeletePlaylistByIdErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type DeletePlaylistByIdError = DeletePlaylistByIdErrors[keyof DeletePlaylistByIdErrors];

export type DeletePlaylistByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};
